language: haxe
haxe:
  - "3.2.0"
  - "3.2.1"
neko: "2.0.0"
install:
  - chmod +x travis/setup.sh
  - source travis/setup.sh
script: cd ${TRAVIS_BUILD_DIR}/travis && haxe js.hxml && mocha ${TRAVIS_BUILD_DIR}/spec/runTests.js -t 5000
env:
    - NG_VERSION=2.0.0-beta.4
    - NG_VERSION=2.0.0-beta.5
    - NG_VERSION=2.0.0-beta.6
